services:
  lxqt:
    # build: .
    image: dkge/debian-xfce-vnc:latest
    container_name: debian-xfce-vnc
    ports:
      - "6080:6080"
    environment:
      - VNC_PASSWORD=yourpassword
      - VNC_RESOLUTION=1600x900
      - VNC_DEPTH=24
    volumes:
      - ./data:/opt/data
    restart: unless-stopped
